[*] Running ...
[*] Dataset loaded: C:\Development\cs5491-artificial-intelligence/problems/tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "C:\Development\cs5491-artificial-intelligence/problems/tsp_constructive/eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Development\cs5491-artificial-intelligence/problems/tsp_constructive/eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
                ^^^^^^^^^^^^^^^^^
  File "C:\Development\cs5491-artificial-intelligence\problems\tsp_constructive\gpt.py", line 18, in select_next_node_v2
    all_distances = [distance_matrix[next_node][j] for j in next_nodes if j != next_node]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'next_node'
